apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: node-github-actions-artifactory-140425-gitops
  description: This is GitOps manifest for node-github-actions-artifactory-140425   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=node-github-actions-artifactory-140425
    backstage.io/kubernetes-id: node-github-actions-artifactory-140425 
    backstage.io/techdocs-ref: dir:. 
    github.com/project-slug: rhtap-qe-jsmid/node-github-actions-artifactory-140425-gitops
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:node-github-actions-artifactory-140425
